# Generated by Django 5.0.1 on 2024-02-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSystemApp', '0002_friendslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
