# Generated by Django 5.0.1 on 2024-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSystemApp', '0006_room_roommessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessages',
            name='user_name',
            field=models.CharField(max_length=1000),
        ),
    ]
